version: '3.8'

services:
  wazuh-mcp-server:
    build: .
    container_name: wazuh-mcp-server
    restart: unless-stopped
    
    # Environment variables - uses .env file if it exists
    environment:
      # Wazuh Configuration
      - WAZUH_HOST=${WAZUH_HOST:-localhost}
      - WAZUH_PORT=${WAZUH_PORT:-55000}
      - WAZUH_USER=${WAZUH_USER:-admin}
      - WAZUH_PASS=${WAZUH_PASS:-admin}
      - VERIFY_SSL=${VERIFY_SSL:-false}
      - WAZUH_API_VERSION=${WAZUH_API_VERSION:-v4}
      
      # External API Keys
      - VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY:-}
      - SHODAN_API_KEY=${SHODAN_API_KEY:-}
      - ABUSEIPDB_API_KEY=${ABUSEIPDB_API_KEY:-}
      
      # Server Configuration
      - DEBUG=${DEBUG:-false}
      - MCP_SERVER_PORT=${MCP_SERVER_PORT:-8000}
      
      # Performance Settings
      - MAX_ALERTS_PER_QUERY=${MAX_ALERTS_PER_QUERY:-1000}
      - MAX_AGENTS_PER_SCAN=${MAX_AGENTS_PER_SCAN:-10}
      - CACHE_TTL_SECONDS=${CACHE_TTL_SECONDS:-300}
      - REQUEST_TIMEOUT_SECONDS=${REQUEST_TIMEOUT_SECONDS:-30}
      
      # Feature Flags
      - ENABLE_EXTERNAL_INTEL=${ENABLE_EXTERNAL_INTEL:-true}
      - ENABLE_ML_ANALYSIS=${ENABLE_ML_ANALYSIS:-true}
      - ENABLE_COMPLIANCE_CHECKING=${ENABLE_COMPLIANCE_CHECKING:-true}
      
      # Python Configuration
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    
    # Volumes
    volumes:
      # Logs directory
      - ./logs:/app/logs
      
      # Data directory for cache/temp files
      - ./data:/app/data
      
      # Mount .env file if you prefer file-based config (optional)
      # - ./.env:/app/.env:ro
      
      # For development: mount source code
      # - ./src:/app/src:ro
    
    # Networks
    networks:
      - mcp-network
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=wazuh-mcp"
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Read-only root filesystem for security
    read_only: true
    
    # Temp directories for writable areas
    tmpfs:
      - /tmp
      - /app/.cache

  # Optional: Add a init container to create .env if missing
  init-env:
    image: busybox:latest
    container_name: wazuh-mcp-init
    command: |
      sh -c '
        if [ ! -f /config/.env ]; then
          echo "Creating .env from .env.example..."
          cp /config/.env.example /config/.env 2>/dev/null || {
            echo "Creating default .env file..."
            cat > /config/.env << EOF
      # Wazuh Configuration
      WAZUH_HOST=localhost
      WAZUH_PORT=55000
      WAZUH_USER=admin
      WAZUH_PASS=admin
      VERIFY_SSL=false
      
      # External API Keys (Optional)
      VIRUSTOTAL_API_KEY=
      SHODAN_API_KEY=
      ABUSEIPDB_API_KEY=
      
      # Server Configuration
      DEBUG=false
      EOF
          }
          echo "IMPORTANT: Edit .env with your Wazuh credentials!"
        else
          echo ".env file already exists"
        fi
      '
    volumes:
      - .:/config
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# Optional: Volume definitions for persistence
volumes:
  logs:
    driver: local
  data:
    driver: local