global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Wazuh MCP Server HTTP
  - job_name: 'wazuh-mcp-http'
    static_configs:
      - targets: ['wazuh-mcp-http:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Wazuh MCP Server WebSocket
  - job_name: 'wazuh-mcp-ws'
    static_configs:
      - targets: ['wazuh-mcp-ws:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Traefik
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']