# Grafana Alerting Rules for Wazuh MCP Server v3.0.0
# This file contains Grafana-specific alerting rules and dashboards

apiVersion: 1

groups:
  - name: wazuh-mcp-grafana-alerts
    orgId: 1
    folder: alerts
    interval: 1m
    
    rules:
      - uid: wazuh-mcp-server-health
        title: Wazuh MCP Server Health
        condition: B
        data:
          - refId: A
            queryType: prometheus
            model:
              expr: up{job="wazuh-mcp-servers"}
              interval: 10s
              refId: A
          - refId: B
            queryType: math
            model:
              expression: $A == 0
              reducer: last
              refId: B
        noDataState: NoData
        execErrState: Alerting
        for: 30s
        annotations:
          description: "Wazuh MCP Server {{ $labels.instance }} is down"
          summary: "Server health check failed"
        labels:
          severity: critical
          team: ops
          service: wazuh-mcp-server
      
      - uid: wazuh-mcp-response-time
        title: High Response Time
        condition: B
        data:
          - refId: A
            queryType: prometheus
            model:
              expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="wazuh-mcp-servers"}[5m]))
              interval: 10s
              refId: A
          - refId: B
            queryType: math
            model:
              expression: $A > 2
              reducer: last
              refId: B
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          description: "95th percentile response time is {{ $value }}s for {{ $labels.instance }}"
          summary: "High response time detected"
        labels:
          severity: high
          team: ops
          service: wazuh-mcp-server
      
      - uid: wazuh-mcp-error-rate
        title: High Error Rate
        condition: B
        data:
          - refId: A
            queryType: prometheus
            model:
              expr: rate(http_requests_total{job="wazuh-mcp-servers",status=~"5.."}[5m]) / rate(http_requests_total{job="wazuh-mcp-servers"}[5m])
              interval: 10s
              refId: A
          - refId: B
            queryType: math
            model:
              expression: $A > 0.1
              reducer: last
              refId: B
        noDataState: NoData
        execErrState: Alerting
        for: 2m
        annotations:
          description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.instance }}"
          summary: "High error rate detected"
        labels:
          severity: critical
          team: ops
          service: wazuh-mcp-server
      
      - uid: redis-memory-usage
        title: Redis High Memory Usage
        condition: B
        data:
          - refId: A
            queryType: prometheus
            model:
              expr: redis_memory_used_bytes / redis_memory_max_bytes
              interval: 10s
              refId: A
          - refId: B
            queryType: math
            model:
              expression: $A > 0.9
              reducer: last
              refId: B
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          description: "Redis memory usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"
          summary: "Redis memory usage is high"
        labels:
          severity: high
          team: ops
          service: redis
      
      - uid: container-restart-loop
        title: Container Restart Loop
        condition: B
        data:
          - refId: A
            queryType: prometheus
            model:
              expr: increase(container_restart_count[1h])
              interval: 10s
              refId: A
          - refId: B
            queryType: math
            model:
              expression: $A > 5
              reducer: last
              refId: B
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          description: "Container {{ $labels.container_label_com_docker_compose_service }} restarted {{ $value }} times in the last hour"
          summary: "Container is in restart loop"
        labels:
          severity: high
          team: ops
          service: docker
      
      - uid: security-breach
        title: Security Breach
        condition: B
        data:
          - refId: A
            queryType: prometheus
            model:
              expr: wazuh_mcp_security_violations_total
              interval: 10s
              refId: A
          - refId: B
            queryType: math
            model:
              expression: $A > 0
              reducer: last
              refId: B
        noDataState: NoData
        execErrState: Alerting
        for: 0s
        annotations:
          description: "Security violation detected on {{ $labels.instance }}"
          summary: "Security breach detected"
        labels:
          severity: critical
          team: security
          service: wazuh-mcp-server
      
      - uid: certificate-expiry
        title: Certificate Expiry Warning
        condition: B
        data:
          - refId: A
            queryType: prometheus
            model:
              expr: wazuh_mcp_certificate_expiry_days
              interval: 10s
              refId: A
          - refId: B
            queryType: math
            model:
              expression: $A < 30
              reducer: last
              refId: B
        noDataState: NoData
        execErrState: Alerting
        for: 1h
        annotations:
          description: "SSL certificate expires in {{ $value }} days on {{ $labels.instance }}"
          summary: "Certificate expiring soon"
        labels:
          severity: high
          team: ops
          service: wazuh-mcp-server
      
      - uid: backup-failure
        title: Backup Failure
        condition: B
        data:
          - refId: A
            queryType: prometheus
            model:
              expr: wazuh_mcp_backup_status
              interval: 10s
              refId: A
          - refId: B
            queryType: math
            model:
              expression: $A == 0
              reducer: last
              refId: B
        noDataState: NoData
        execErrState: Alerting
        for: 1m
        annotations:
          description: "Last backup failed on {{ $labels.instance }}"
          summary: "Backup failed"
        labels:
          severity: high
          team: ops
          service: wazuh-mcp-server
      
      - uid: disk-space-low
        title: Low Disk Space
        condition: B
        data:
          - refId: A
            queryType: prometheus
            model:
              expr: (node_filesystem_free_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"})
              interval: 10s
              refId: A
          - refId: B
            queryType: math
            model:
              expression: $A < 0.1
              reducer: last
              refId: B
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          description: "Disk space is {{ $value | humanizePercentage }} free on {{ $labels.instance }}"
          summary: "Low disk space"
        labels:
          severity: critical
          team: ops
          service: system
      
      - uid: haproxy-backend-down
        title: HAProxy Backend Down
        condition: B
        data:
          - refId: A
            queryType: prometheus
            model:
              expr: haproxy_server_up
              interval: 10s
              refId: A
          - refId: B
            queryType: math
            model:
              expression: $A == 0
              reducer: last
              refId: B
        noDataState: NoData
        execErrState: Alerting
        for: 30s
        annotations:
          description: "Backend server {{ $labels.server }} in {{ $labels.backend }} is down"
          summary: "HAProxy backend server down"
        labels:
          severity: critical
          team: ops
          service: haproxy

  - name: wazuh-mcp-business-alerts
    orgId: 1
    folder: alerts
    interval: 5m
    
    rules:
      - uid: low-throughput
        title: Low Request Throughput
        condition: B
        data:
          - refId: A
            queryType: prometheus
            model:
              expr: rate(wazuh_mcp_requests_total[5m])
              interval: 10s
              refId: A
          - refId: B
            queryType: math
            model:
              expression: $A < 10
              reducer: last
              refId: B
        noDataState: NoData
        execErrState: Alerting
        for: 10m
        annotations:
          description: "Request rate is {{ $value }} requests/sec on {{ $labels.instance }}"
          summary: "Low request throughput"
        labels:
          severity: medium
          team: ops
          service: wazuh-mcp-server
      
      - uid: authentication-failures
        title: High Authentication Failures
        condition: B
        data:
          - refId: A
            queryType: prometheus
            model:
              expr: rate(wazuh_mcp_auth_failures_total[5m])
              interval: 10s
              refId: A
          - refId: B
            queryType: math
            model:
              expression: $A > 5
              reducer: last
              refId: B
        noDataState: NoData
        execErrState: Alerting
        for: 2m
        annotations:
          description: "Authentication failure rate: {{ $value }} failures/sec on {{ $labels.instance }}"
          summary: "High authentication failure rate"
        labels:
          severity: high
          team: security
          service: wazuh-mcp-server
      
      - uid: queue-backlog
        title: Message Queue Backlog
        condition: B
        data:
          - refId: A
            queryType: prometheus
            model:
              expr: wazuh_mcp_queue_size
              interval: 10s
              refId: A
          - refId: B
            queryType: math
            model:
              expression: $A > 1000
              reducer: last
              refId: B
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          description: "Queue size is {{ $value }} messages on {{ $labels.instance }}"
          summary: "Message queue backlog"
        labels:
          severity: medium
          team: ops
          service: wazuh-mcp-server

  - name: wazuh-mcp-sla-alerts
    orgId: 1
    folder: alerts
    interval: 5m
    
    rules:
      - uid: sla-availability
        title: SLA Availability Violation
        condition: B
        data:
          - refId: A
            queryType: prometheus
            model:
              expr: (1 - (rate(up{job="wazuh-mcp-servers"}[24h]))) * 100
              interval: 10s
              refId: A
          - refId: B
            queryType: math
            model:
              expression: $A > 0.1  # 99.9% availability
              reducer: last
              refId: B
        noDataState: NoData
        execErrState: Alerting
        for: 1m
        annotations:
          description: "Service availability is {{ $value }}% (SLA: 99.9%)"
          summary: "SLA availability violation"
        labels:
          severity: high
          team: ops
          service: wazuh-mcp-server
      
      - uid: sla-response-time
        title: SLA Response Time Violation
        condition: B
        data:
          - refId: A
            queryType: prometheus
            model:
              expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="wazuh-mcp-servers"}[5m]))
              interval: 10s
              refId: A
          - refId: B
            queryType: math
            model:
              expression: $A > 0.5  # 500ms SLA
              reducer: last
              refId: B
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          description: "95th percentile response time is {{ $value }}s (SLA: 500ms)"
          summary: "SLA response time violation"
        labels:
          severity: high
          team: ops
          service: wazuh-mcp-server
      
      - uid: sla-error-rate
        title: SLA Error Rate Violation
        condition: B
        data:
          - refId: A
            queryType: prometheus
            model:
              expr: rate(http_requests_total{job="wazuh-mcp-servers",status=~"5.."}[5m]) / rate(http_requests_total{job="wazuh-mcp-servers"}[5m]) * 100
              interval: 10s
              refId: A
          - refId: B
            queryType: math
            model:
              expression: $A > 1  # 1% error rate SLA
              reducer: last
              refId: B
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          description: "Error rate is {{ $value }}% (SLA: <1%)"
          summary: "SLA error rate violation"
        labels:
          severity: high
          team: ops
          service: wazuh-mcp-server